### ISSUE TITLE
capital_base argument of run_algorithm function in live trading

### ISSUE THREAD

**Issue by vaa1234** [alphaville76/sharadar_db_bundle#21]
Hi!

Does capital_base affect the algorithm in live trading? In theory, it should.

Now order_target_percent calculates the number of shares based on net liquidation value of brokerage account, not on capital_base.

I wanted to solve another problem. For example, IB account size is 100000. I want to allocate 10000 for the strategy through the capital_base argument of run_algorithm function. Next, I want to get the portfolio_value at the end of each trading day and substitute this value into the capital_base argument at the next launch. With this approach in context.portfolio, as far as I understand (correct me if this is not so) there will always be the actual sum of the assets of the strategy and functions of the order_target_percent type will work correctly.

Tell me, if it's not a secret, how do you solve the problem of dividing the account into several strategies?

Sincerely, Alexander

**Comment by alphaville76** [comment]
Hi Alexander,
I simply have a dedicated account pro strategy (they are only 2)

**Comment by vaa1234** [comment]
I understand. This approach is simple, but not very comfortable for me. Thanks for the answer.
