### ISSUE TITLE
ImportError: No module named 'zipline.data.data_portal_live'

### ISSUE THREAD

**Issue by vaa1234** [alphaville76/sharadar_db_bundle#3]
Hi!

When i try to 
$ ./sharadar-zipline.sh ingest

i get error:

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
    from sharadar.util.run_algo import _run, load_extensions
  File "/Users/xxx/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/sharadar_db_bundle-1.0-py3.5.egg/sharadar/util/run_algo.py", line 24, in <module>
    from zipline.data.data_portal_live import DataPortalLive
ImportError: No module named 'zipline.data.data_portal_live'

I understand correctly that this lib is not in the standard installation of zipline, and you created it? Could you add it to the repository so that everything works correctly? Thanks.

**Comment by alphaville76** [comment]
yes, it's based on zipline-live2: https://github.com/shlomikushchi/zipline-live2
In the future, I'll migrate to https://github.com/shlomikushchi/zipline-trader

**Comment by vaa1234** [comment]
Thanks, I got it. I will try. if I can run your code properly, it will be wonderful. Integrating fundamental data into zipline is a nightmare.
